# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/redrob1n/VivadoProjects/MicroBlazeIP/MicroBlazeIP.srcs/sources_1/bd/MicroBlazeIP/ip/MicroBlazeIP_xbar_0/MicroBlazeIP_xbar_0.xci
# IP: The module: 'MicroBlazeIP_xbar_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/redrob1n/VivadoProjects/MicroBlazeIP/MicroBlazeIP.gen/sources_1/bd/MicroBlazeIP/ip/MicroBlazeIP_xbar_0/MicroBlazeIP_xbar_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'MicroBlazeIP_xbar_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: C:/Users/redrob1n/VivadoProjects/MicroBlazeIP/MicroBlazeIP.srcs/sources_1/bd/MicroBlazeIP/ip/MicroBlazeIP_xbar_0/MicroBlazeIP_xbar_0.xci
# IP: The module: 'MicroBlazeIP_xbar_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/redrob1n/VivadoProjects/MicroBlazeIP/MicroBlazeIP.gen/sources_1/bd/MicroBlazeIP/ip/MicroBlazeIP_xbar_0/MicroBlazeIP_xbar_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'MicroBlazeIP_xbar_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
