# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: C:/Users/redrob1n/Downloads/digilent-xdc-master/digilent-xdc-master/Arty-A7-100-Master.xdc

# Block Designs: bd/MicroBlazeIP/MicroBlazeIP.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==MicroBlazeIP || ORIG_REF_NAME==MicroBlazeIP} -quiet] -quiet

# IP: bd/MicroBlazeIP/ip/MicroBlazeIP_microblaze_0_0/MicroBlazeIP_microblaze_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==MicroBlazeIP_microblaze_0_0 || ORIG_REF_NAME==MicroBlazeIP_microblaze_0_0} -quiet] -quiet

# IP: bd/MicroBlazeIP/ip/MicroBlazeIP_mig_7series_0_0/MicroBlazeIP_mig_7series_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==MicroBlazeIP_mig_7series_0_0 || ORIG_REF_NAME==MicroBlazeIP_mig_7series_0_0} -quiet] -quiet

# IP: bd/MicroBlazeIP/ip/MicroBlazeIP_dlmb_v10_1/MicroBlazeIP_dlmb_v10_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==MicroBlazeIP_dlmb_v10_1 || ORIG_REF_NAME==MicroBlazeIP_dlmb_v10_1} -quiet] -quiet

# IP: bd/MicroBlazeIP/ip/MicroBlazeIP_ilmb_v10_1/MicroBlazeIP_ilmb_v10_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==MicroBlazeIP_ilmb_v10_1 || ORIG_REF_NAME==MicroBlazeIP_ilmb_v10_1} -quiet] -quiet

# IP: bd/MicroBlazeIP/ip/MicroBlazeIP_dlmb_bram_if_cntlr_1/MicroBlazeIP_dlmb_bram_if_cntlr_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==MicroBlazeIP_dlmb_bram_if_cntlr_1 || ORIG_REF_NAME==MicroBlazeIP_dlmb_bram_if_cntlr_1} -quiet] -quiet

# IP: bd/MicroBlazeIP/ip/MicroBlazeIP_ilmb_bram_if_cntlr_1/MicroBlazeIP_ilmb_bram_if_cntlr_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==MicroBlazeIP_ilmb_bram_if_cntlr_1 || ORIG_REF_NAME==MicroBlazeIP_ilmb_bram_if_cntlr_1} -quiet] -quiet

# IP: bd/MicroBlazeIP/ip/MicroBlazeIP_lmb_bram_1/MicroBlazeIP_lmb_bram_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==MicroBlazeIP_lmb_bram_1 || ORIG_REF_NAME==MicroBlazeIP_lmb_bram_1} -quiet] -quiet

# IP: bd/MicroBlazeIP/ip/MicroBlazeIP_mdm_1_1/MicroBlazeIP_mdm_1_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==MicroBlazeIP_mdm_1_1 || ORIG_REF_NAME==MicroBlazeIP_mdm_1_1} -quiet] -quiet

# IP: bd/MicroBlazeIP/ip/MicroBlazeIP_rst_mig_7series_0_81M_0/MicroBlazeIP_rst_mig_7series_0_81M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==MicroBlazeIP_rst_mig_7series_0_81M_0 || ORIG_REF_NAME==MicroBlazeIP_rst_mig_7series_0_81M_0} -quiet] -quiet

# IP: bd/MicroBlazeIP/ip/MicroBlazeIP_axi_smc_0/MicroBlazeIP_axi_smc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==MicroBlazeIP_axi_smc_0 || ORIG_REF_NAME==MicroBlazeIP_axi_smc_0} -quiet] -quiet

# IP: bd/MicroBlazeIP/ip/MicroBlazeIP_axi_uartlite_0_0/MicroBlazeIP_axi_uartlite_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==MicroBlazeIP_axi_uartlite_0_0 || ORIG_REF_NAME==MicroBlazeIP_axi_uartlite_0_0} -quiet] -quiet

# IP: bd/MicroBlazeIP/ip/MicroBlazeIP_xbar_0/MicroBlazeIP_xbar_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==MicroBlazeIP_xbar_0 || ORIG_REF_NAME==MicroBlazeIP_xbar_0} -quiet] -quiet

# IP: bd/MicroBlazeIP/ip/MicroBlazeIP_microblaze_0_axi_periph_0/MicroBlazeIP_microblaze_0_axi_periph_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==MicroBlazeIP_microblaze_0_axi_periph_0 || ORIG_REF_NAME==MicroBlazeIP_microblaze_0_axi_periph_0} -quiet] -quiet

# IP: bd/MicroBlazeIP/ip/MicroBlazeIP_axi_gpio_0_2/MicroBlazeIP_axi_gpio_0_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==MicroBlazeIP_axi_gpio_0_2 || ORIG_REF_NAME==MicroBlazeIP_axi_gpio_0_2} -quiet] -quiet

# IP: bd/MicroBlazeIP/ip/MicroBlazeIP_axi_gpio_0_3/MicroBlazeIP_axi_gpio_0_3.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==MicroBlazeIP_axi_gpio_0_3 || ORIG_REF_NAME==MicroBlazeIP_axi_gpio_0_3} -quiet] -quiet

# IP: bd/MicroBlazeIP/ip/MicroBlazeIP_axi_iic_0_0/MicroBlazeIP_axi_iic_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==MicroBlazeIP_axi_iic_0_0 || ORIG_REF_NAME==MicroBlazeIP_axi_iic_0_0} -quiet] -quiet

# IP: bd/MicroBlazeIP/ip/MicroBlazeIP_pwm_gen_0_0/MicroBlazeIP_pwm_gen_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==MicroBlazeIP_pwm_gen_0_0 || ORIG_REF_NAME==MicroBlazeIP_pwm_gen_0_0} -quiet] -quiet

# XDC: c:/Users/redrob1n/VivadoProjects/MicroBlazeIP/MicroBlazeIP.gen/sources_1/bd/MicroBlazeIP/MicroBlazeIP_ooc.xdc
